# General

quarkus.http.root-path = /api

# Logging

quarkus.log.level = INFO
quarkus.log.category."com.shopbee.sample".level = WARN
quarkus.log.console.format = %d{yyyy-MM-dd HH:mm:ss,SSS} - %-5p [%h] [%i] [%t{id}] [%c] %X{logInformation} - %m%n

# Datasource

%prod.quarkus.datasource.db-kind = ${DATABASE_KIND:postgresql}
%prod.quarkus.datasource.username = ${DATABASE_USERNAME}
%prod.quarkus.datasource.password = ${DATABASE_PASSWORD}
%prod.quarkus.datasource.jdbc.url = ${DATABASE_JDBC_URL}
%prod.quarkus.datasource.jdbc.max-size = ${DATABASE_JDBC_MAXSIZE:10}
%prod.quarkus.hibernate-orm.database.generation = none
%prod.quarkus.hibernate-orm.sql-load-script = no-file

# Build configuration, can be passed during build time

#quarkus.kubernetes.namespace = shopbee
#quarkus.kubernetes.idempotent = true
#quarkus.kubernetes.image-pull-policy = IfNotPresent
#quarkus.kubernetes.env.vars.database-kind = ${DATABASE_KIND:postgresql}
#quarkus.kubernetes.resources.requests.memory = 64Mi
#quarkus.kubernetes.resources.requests.cpu = 250m
#quarkus.kubernetes.resources.limits.memory = 512Mi
#quarkus.kubernetes.resources.limits.cpu = 500m
#quarkus.kubernetes.ingress.expose = true
#quarkus.kubernetes.ingress.ingress-class-name = nginx
#quarkus.kubernetes.ingress.host = api.shopbee.com.local
#quarkus.kubernetes.ports.http.path = /api/hello
#quarkus.kubernetes.deploy = false
#quarkus.container-image.build = false
#quarkus.container-image.registry = com.shopbee
#quarkus.container-image.image = com.shopbee/shopbee-sample-service:1.0.0
#quarkus.docker.dockerfile-jvm-path = ./Dockerfile
#quarkus.container-image.push = false