# Gradle properties

quarkusPluginId           = io.quarkus
quarkusPluginVersion      = 3.23.0
quarkusPlatformGroupId    = io.quarkus.platform
quarkusPlatformArtifactId = quarkus-bom
quarkusPlatformVersion    = 3.23.0

# Project metadata

projectGroupId            = com.shopbee
projectPackageId          = com.shopbee.user
projectArtifactId         = shopbee-user-service
projectVersion            = 1.0.1

# Gradle settings
org.gradle.jvmargs        = -Xmx1g -Xms512m

