openapi: "3.0.3"
info:
  version: 0.0.1
  title: Tenant Management API
  description: This is the API documentation for the Tenant Management API.
  license:
    name: Copyright by Shopbee, all rights reserved.

paths:
  /tenants:
    get:
      summary: Get all tenants
      operationId: getTenants
      tags:
        - tenants
      responses:
        200:
          description: A list of tenants
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TenantDTO"
    post:
      summary: Create a tenant
      operationId: createTenant
      tags:
        - tenants
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/TenantDTO"
                - type: object
                  properties:
                    id:
                      readOnly: true
                  required:
                    - name
                    - subdomain
                    - adminEmail

      responses:
        201:
          description: Created tenant
          headers:
            Location:
              description: URL of the created tenant
              schema:
                type: string
                format: uri
                example: "/tenants/shopbee"
        400:
          description: "Bad Request: The request is invalid due to malformed syntax or validation error"
        401:
          description: "Unauthorized: JWT token is missing or invalid"
        403:
          description: "Forbidden: The caller does not have permission"
        409:
          description: "Conflict: The request could not be completed due to a conflict with the current state of the resource"
        500:
          description: "Internal Server Error: An unexpected error occurred"
        501:
          description: "Not Implemented: The operation is not implemented"
        503:
          description: "Service Unavailable: The service is temporarily unavailable"

  /tenants/{tenantId}:
    get:
      summary: Get tenant by id
      operationId: getTenantById
      tags:
        - tenants
      parameters:
        - $ref: "#/components/parameters/tenantId"
      responses:
        200:
          description: The tenant found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TenantDTO"
        401:
          description: "Unauthorized: JWT token is missing or invalid"
        403:
          description: "Forbidden: The caller does not have permission"
        500:
          description: "Internal Server Error: An unexpected error occurred"
        501:
          description: "Not Implemented: The operation is not implemented"
        503:
          description: "Service Unavailable: The service is temporarily unavailable"

    put:
      summary: Update tenant by id
      operationId: updateTenantById
      tags:
        - tenants
      parameters:
        - $ref: "#/components/parameters/tenantId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/TenantDTO"
                - type: object
                  properties:
                    id:
                      readOnly: true
                  required:
                    - name
                    - subdomain
                    - adminEmail
      responses:
        200:
          description: "Updated tenant"
        400:
          description: "Bad Request: The request is invalid due to malformed syntax or validation error"
        401:
          description: "Unauthorized: JWT token is missing or invalid"
        403:
          description: "Forbidden: The caller does not have permission"
        409:
          description: "Conflict: The request could not be completed due to a conflict with the current state of the resource"
        500:
          description: "Internal Server Error: An unexpected error occurred"
        501:
          description: "Not Implemented: The operation is not implemented"
        503:
          description: "Service Unavailable: The service is temporarily unavailable"

    delete:
      summary: Delete tenant by id
      operationId: deleteTenantById
      tags:
        - tenants
      parameters:
        - $ref: "#/components/parameters/tenantId"
      responses:
        204:
          description: "Deleted tenant"
        401:
          description: "Unauthorized: JWT token is missing or invalid"
        403:
          description: "Forbidden: The caller does not have permission"
        500:
          description: "Internal Server Error: An unexpected error occurred"
        501:
          description: "Not Implemented: The operation is not implemented"
        503:
          description: "Service Unavailable: The service is temporarily unavailable"

components:
  schemas:
    TenantDTO:
      properties:
        id:
          type: string
          maxLength: 64
          minLength: 8
          description: Unique identifier for the tenant
          example: "shopbee"
        name:
          type: string
          maxLength: 255
          minLength: 8
          description: Name of the tenant
          example: "Shopbee"
        subdomain:
          type: string
          maxLength: 255
          minLength: 3
          description: Subdomain for the tenant
          example: "shopbee"
        adminEmail:
          type: string
          format: email
          maxLength: 255
          description: Admin email for the tenant
          example: "shopbee.admin@shopbee.com"
  parameters:
    tenantId:
      name: tenantId
      in: path
      required: true
      description: The id of the tenant
      schema:
        type: string
        maxLength: 64
        example: "shopbee"

security:
  - BearerAuth: [ ]