### General configuration

quarkus.http.root-path = /api

### Logging configuration

quarkus.log.level = WARN
quarkus.log.category."com.shopbee.category".level = INFO
quarkus.log.console.format = %d{yyyy-MM-dd HH:mm:ss,SSS} - %-5p [%h] [%i] [%t{id}] [%c] %X{logInformation} - %m%n

### Security configuration

%prod.shopbee.security.auth-server-url = ${AUTH_SERVER_URL}
%prod.shopbee.security.issuer = ${AUTH_ISSUER}
%prod.shopbee.security.client-id = ${AUTH_CLIENT_ID}
%prod.quarkus.oidc.tenant-enabled = false

### Database configuration

%prod.quarkus.datasource.db-kind = ${DATABASE_KIND:postgresql}
%prod.quarkus.datasource.username = ${DATABASE_USERNAME}
%prod.quarkus.datasource.password = ${DATABASE_PASSWORD}
%prod.quarkus.datasource.jdbc.url = ${DATABASE_JDBC_URL}
%prod.quarkus.datasource.jdbc.max-size = ${DATABASE_JDBC_MAXSIZE:10}
%prod.quarkus.hibernate-orm.database.generation = none
%prod.quarkus.liquibase.migrate-at-start = true

### Test configuration

%test.quarkus.http.test-port = 0
%test.quarkus.log.category."com.shopbee.category".level = DEBUG

### Dev configuration

%dev.quarkus.http.port = 9000
%dev.quarkus.http.host = 0.0.0.0
%dev.quarkus.devservices.enabled = false

%dev.quarkus.log.category."com.shopbee.category".level = DEBUG
%dev.quarkus.log.console.enable = true
%dev.quarkus.log.console.color = true
%dev.quarkus.log.console.format = %d{yyyy-MM-dd HH:mm:ss,SSS} - %-5p [%h] [%i] [%t{id}] [%c] %X{logInformation} - %m%n

%dev.shopbee.security.auth-server-url = http://shopbee-keycloak:8080/realms/master
%dev.shopbee.security.issuer = http://shopbee-keycloak:8080/realms/master
%dev.shopbee.security.client-id = shopbee
%dev.quarkus.oidc.tenant-enabled = false

%dev.quarkus.hibernate-orm.database.generation = none
%dev.quarkus.liquibase.migrate-at-start = true
%dev.quarkus.liquibase.clean-at-start = true
#%dev.quarkus.hibernate-orm.sql-load-script = import.sql
%dev.quarkus.hibernate-orm.log.sql = true
%dev.quarkus.hibernate-orm.log.format-sql = false
%dev.quarkus.datasource.db-kind = postgresql
%dev.quarkus.datasource.username = postgres
%dev.quarkus.datasource.password = admin
%dev.quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/shopbee
